name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: my_thesis.tex

      # From https://github.com/latextemplates/scientific-thesis-template/blob/main/.github/workflows/build-and-publish-with-latexmk.yml
      - name: Gather build artifacts
        run: mkdir build && cp my_thesis.pdf build/thesis.pdf && cp -r docs/* build/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: true
